# -*- coding: utf-8 -*-
"""Followertracker.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DOxCgLqLXugwV9IOLsusOeK4dBkvvPGA
"""

pip install instaloader

from instaloader import instaloader, Profile

# Create an instance of Instaloader
L = instaloader.Instaloader()
#enter your username and password
try:
  L.login("", "")
except:#enter your two-factor authentication code if applicable
  L.two_factor_login()

# Get the profile of the account you want to check
profile = instaloader.Profile.from_username(L.context, "")

# Retrieve the followings
followees = profile.get_followees()
y = []
# save the list
for f in followees:
  y.append(str(f.username))

# Retreive the followers
followers = profile.get_followers()
x = []
for follower in followers:
  x.append(str(follower.username))

a = 0
print("The people that do not follow you back are: ")
#check for people that don't follow back
for n in y:
  if n not in x:
    print(n)
    a+=1
print (f"You follow {a} people that do not follow you back.")